### ISSUE TITLE
ZeroDivisionError: division by zero

### ISSUE THREAD

**Issue by Yjh-Rking** [B1ACK917/2021HWAutoGrader#2]
Traceback (most recent call last):
  File "autograder.py", line 248, in <module>
    _ = grader(testCmd, d)
  File "autograder.py", line 212, in grader
    emptyRate), 10 / 10, folderName, migTot, bombInfo

**Comment by Yjh-Rking** [comment]
> Traceback (most recent call last):
> File "autograder.py", line 248, in
> _ = grader(testCmd, d)
> File "autograder.py", line 212, in grader
> emptyRate), 10 / 10, folderName, migTot, bombInfo
